### ISSUE TITLE
log command crashes

### ISSUE THREAD

**Issue by leamas** [mmueller/supybot-git#11]
As heading says, log command crashes randomly. A quick debug tour indicates that this is some kind of  name collision between the log object and the log method - getCommandMethod in supybot/callbacks.py fails around line 1170.

**Comment by mmueller** [comment]
Yeah, this is a supybot bug. See the note at the bottom of the supybot-git README or issue #9 for more.  The workaround is:

```
@defaultplugin log Git
```
