### ISSUE TITLE
LIcensing issues.

### ISSUE THREAD

**Issue by leamas** [mmueller/supybot-git#16]
Although I presume you have used a permissive license in order to make it easy to use this plugin there are some issues.

The first is that the legal consequences of the patched BSD license you are using ("Do whatever you want" ) are unclear. To be frank, to use this in a distribution legal advices is probably needed.

The second is that this change is not consistent: the **init** file has the original BSD 3-clause license giving the whole package an ever more complicated  (mixed) legal status.

In my fork I have solved this by simply relicensing all files using the original BSD 3-clause license used in **init**.py, taking the words "Do whatever you want" as giving me this right. If you have any objections, please let me know ASAP. After all, you are the copyright owner.

**Comment by mmueller** [comment]
Supybot generates the copyright messages at the top of each file when you use the script to generate a plugin scaffold. If the 3-clause BSD license makes it easier for you, please feel free to use it.
