### ISSUE TITLE
BadObject errors.

### ISSUE THREAD

**Issue by ShadowNinja** [mmueller/supybot-git#17]
I am getting at least two BadObject errors, the plugin still seems to work.
I am running git HEAD of this plugin and the Limnoria testing branch.

http://pastebin.ubuntu.com/5638825/

**Comment by mmueller** [comment]
Are you running the latest supybot-git from Github? I believe this is
fixed, but maybe there's another way for it to happen...

**Comment by ShadowNinja** [comment]
Well seems it isn't fixed, I am running latest.

**Comment by andrejb** [comment]
Hello, I'm getting a BadObject error when the configured branch does not exist for a repo. I'm using the latest code in master branch.

To reproduce, I configured a github repo (using git:// protocol) with a non-existent branch name, and then I rehash. In the chat window, I get:

```
Warning: BadObject: 6f726967696e2f646576656c6f706570657065
```

In supybot's output (using --debug), I get:

```
WARNING 2013-05-15T21:31:11 Git: BadObject:
        6f726967696e2f646576656c6f706570657065
```

Is there some way to give you more info that might help?

Thanks for the great software.
