### ISSUE TITLE
Is it possible to announce Pull Requests?

### ISSUE THREAD

**Issue by adinapoli** [mmueller/supybot-git#21]
Hello there,

thanks for your fantastic plugin :)

We are using the plugin within our company's IRC, and it would be nice to have the Pull Request announced (on our master repo) instead than individual commits. Is that possible using Github webhooks?

Thanks!
A.

**Comment by mmueller** [comment]
It's probably possible, but this plugin isn't meant to be Github-specific. If someone wrote a Github-specific plugin, it would probably have a very different implementation using their API.

**Comment by adinapoli** [comment]
For the curious, I've discovered it's possible using Github IRC hook. Posting here in case someone stumbles upon this discussion :)
