### ISSUE TITLE
supybot does not load supybot-git plugin

### ISSUE THREAD

**Issue by shiznix** [mmueller/supybot-git#26]
How do I configure supybot to load this plugin ?

This info seems to be missing from the README.

**Comment by shiznix** [comment]
OK through some trial and error with renaming the plugin directory and editing supybot's config file, the plugin now loads but it breaks supybot being able to connect to the IRC server :(

**Comment by mmueller** [comment]
This is really a supybot question. You should be able to just tell it `load Git` to load the plugin. The plugin should be in a folder called 'Git' in your plugins directory.

**Comment by shiznix** [comment]
Thanks for your response, i've opened issue #27 regarding the IRC connection hang.
