### ISSUE TITLE
Bot kicked when repo unavailable

### ISSUE THREAD

**Issue by CiaranG** [mmueller/supybot-git#4]
If a repo being monitored becomes unavailable (which I have just seen as a result of some scheduled gitorious.org downtime) the bot seems to be spending an excessively long time trying to contact it, which has the knock-on effect of it missing a ping from the IRC server and getting it disconnected. This results in an irritating "joined the channel"  + "disconnected (ping timeout)" loop until connectivity to the repo is restored.

I'm not sure if this is fixable within the code itself, or whether something might have to be done at system level to make it time out quicker? If nothing else, it's probably worth a mention in the documentation.

**Comment by mmueller** [comment]
Just moved the polling to a separate thread.  This should be fixed now.

**Comment by CiaranG** [comment]
Ok, super long delay in responding, but I had to wait for a long gitorious outage that coincided with me being around to see what happened when I upgraded. I can confirm it's fixed, and thanks very much for that. :)

**Comment by mmueller** [comment]
Thanks for the feedback, glad it worked!
