### ISSUE TITLE
Option request.

### ISSUE THREAD

**Issue by w1sht0l1v3** [mmueller/supybot-git#7]
Hi is it possible to add support for multiple channels for one repo?(example: channel = #chan1,#chan2,#chan3)
If possible in such a way it would support multiple networks also(example: Network plugin loaded and the bot resides on 2 irc networks on different channels).

**Comment by mmueller** [comment]
Right now the plugin does support running on multiple networks, but it only looks at channel name to decide it a repository should be visible or not. (So #supybot on network1 and network2 would be treated the same.)

I'll see if there's a straightforward way to handle this better, and support multiple channels per repository.

As far as new commit notifications, would you expect them to show up on all three channels, or that the repository would have a "primary" channel for announcements?

**Comment by w1sht0l1v3** [comment]
Well,it would be fine to post on all channels assigned to a repo,like cia.vc bot did.

example:
#chan1 is on network 1
#chan2 is on network 2
#chan3 is on network 2

-cycle all channels and post notification in each.
